#!/usr/bin/perl 
#===============================================================================
#
#         FILE: poerator.pl
#
#        USAGE: ./poerator.pl  
#
#  DESCRIPTION: operator
#
#      OPTIONS: ---
# REQUIREMENTS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: yao wen qiang (), yaowenqiang111@163.com
# ORGANIZATION: 
#      VERSION: 1.0
#      CREATED: 2012/05/15 22时13分43秒
#     REVISION: ---
#===============================================================================

use strict;
use warnings;

main(@ARGV);


sub main {
    # $a = 42 + 12;
    # print $a;
    # $b = 42 - 12;
    # print $b;
    # my $c = 42*12;
    # print $c;
    # my $d = 42 / 12;
    # print $d;

    # my $n = 42;
    # $n++;
    # ++$n;
    # $n--;
    # print ++$n;
    # print $n++;
    if(5 == 5) {
        print ("This is true");
    } else{
        print ("This is false");
    }
    return ;
} ## --- end sub main
